### ISSUE TITLE
Highlighting text with background colors is wonky.

### ISSUE THREAD

**Issue by ghost** [mkdynamic/made-of-code-atom#1]
![screen shot 2015-02-19 at 7 30 52 pm](https://cloud.githubusercontent.com/assets/45108/6280626/f6484a88-b86d-11e4-8974-62d0b3837d81.png)

**Comment by bowerman** [comment]
Does atom support highlighting over text that has a background-color?

**Comment by ghost** [comment]
Just going to remove the `background-color` from strings for now.
